function cable_v = CalcCableVectorsD(cable_p,cable_v)

cable_v.vers_n_deriv = cable_v.vers_w.*cos(cable_v.tan_ang).*cable_v.swivel_ang_vel -...
  cable_v.vers_rho.*cable_v.tan_ang_vel;
cable_v.vers_rho_deriv = cable_v.vers_w.*sin(cable_v.tan_ang).*cable_v.swivel_ang_vel +...
  cable_v.vers_n.*cable_v.tan_ang_vel;
cable_v.vel_BA_glob = cable_v.vel_OA_glob-cable_p.swivel_pulley_r.*...
  (cable_v.vers_w.*(1+cos(cable_v.tan_ang)).*cable_v.swivel_ang_vel - ...
  cable_v.vers_rho.*cable_v.tan_ang_vel);

end